name: Lint & Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout

      - name: Set up Python
        uses: actions/setup-python
        with:
          python-version: 3.9.9

      - name: Restore package cache
        uses: actions/cache
        with:
          path: arn.venv
          key: deps-v1-${{ hashFiles('setup.py') }}

      - name: Setup venv
        run: script/bootstrap

      - name: Save Package Cache
        uses: actions/cache@v2
        with:
          path: arn.venv
          key: deps-v1-${{ hashFiles('setup.py') }}

      - name: Run lint
        run: script/lint

      - name: Run tests
        run: script/test
